[tool.poetry]
name = "islets"
version = "0.7.4"
description = ""
authors = [
  "Srdjan Sarikas <srdjan.sarikas@meduniwien.ac.at>",
  "Johannes Pfabe <johannes.pfabe@meduniwien.ac.at>"
]

[tool.poetry.dependencies]
python = "^3.8"
python-javabridge = "^4.0.3"
python-bioformats = "^4.0.6"
plotly = "^5.9.0"
dash = "^2.6.1"
pandas="1.3.5"
scikit-learn = "^1.1"
scikit-image = "^0.19"
tqdm = "^4.64"
bidict = "^0.22"
xlrd = "^2.0"
scipy = "^1.9"
matplotlib = "^3.5"
statsmodels = "^0.13"
opencv-python = "^4.6"
numba = "^0.56"
ffmpeg-python = "^0.2.0"
nd2reader = "^3.3"
mgzip = "^0.2"
orjson = "^3.7"
openpyxl = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
