#!/bin/bash
texwfile=$1
texfile=${texwfile%.texw}.tex
pweave -f texminted $texwfile
pdflatex -shell-escape $texfile
bibtex $texfile
pdflatex -shell-escape $texfile
pdflatex -shell-escape $texfile
rm ${texfile%.tex}.out
rm ${texfile%.tex}.log
rm ${texfile%.tex}.aux
