#!/bin/bash
texwfile=$1
texfile=${texwfile%.texw}.tex
pygmentize -f tex -S default > pygments.sty
pweave -f texpygments $texwfile
pdflatex $texfile
pdflatex $texfile
pdflatex $texfile
rm ${texfile%.tex}.out
rm ${texfile%.tex}.log
rm ${texfile%.tex}.aux
#pweave -s ipython -f texpygments $1.texw
#cp FIR_design_pygments.tex FIR_design_pygments_ipy.tex
#pdflatex FIR_design_pygments_ipy.tex
